version: '3.8'

x-project-name: simple_bank

services:
  angular_app:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "5000:5000"
    volumes:
      - ./api_gateway/.env:/app/.env
    depends_on:
      - user_service
      - account_service
      - deposit_service
      - withdrawal_service
      - historical_service

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_ADDRESS=0.0.0.0:50051
    ports:
      - "50051:50051"
    volumes:
      - ./user_service/.env:/app/.env
  account_service:
    build:
      context: ./account_service
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_ADDRESS=0.0.0.0:50052
    ports:
      - "50052:50052"
    volumes:
      - ./account_service/.env:/app/.env

  deposit_service:
    build:
      context: ./deposit_service
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_ADDRESS=0.0.0.0:50053
    ports:
      - "50053:50053"
    volumes:
      - ./deposit_service/.env:/app/.env

  withdrawal_service:
    build:
      context: ./withdrawal_service
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_ADDRESS=0.0.0.0:50054
    ports:
      - "50054:50054"
    volumes:
      - ./withdrawal_service/.env:/app/.env

  historical_service:
    build:
      context: ./historical_service
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_ADDRESS=0.0.0.0:50055
    ports:
      - "50055:50055"
    volumes:
      - ./historical_service/.env:/app/.env
