[package]
name = "historical_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.6"
tokio = { version = "1", features = ["full"] }
prost = "0.9"
mongodb = "2.0"
dotenv = "0.15"
futures = "0.3"
prost-types = "0.9"

[build-dependencies]
tonic-build = "0.6"